// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Pricing & Packages - Creative Logo Designs",
    description: "Generated by Creative Logo Designs",
    // Google Varification
    verification: {
        // google: 'ziIYRBahP4WcKcps6RWRDJvZ9A00pSoI39ByXDN14us',
        other: {
            "facebook-domain-verification": ['9mgotld2pcip5yvdv6yajdqx71xfvt'],
        },
    },
    // Canonical
    alternates: {
        canonical: 'https://www.creativelogodesigns.io/pricing',
    }
}

export default function RootLayout({ children }) {
    return (children);
}